version: 1.0
os: linux
files:
  - source: target/stock-1.0-SNAPSHOT.jar
    destination: /home/ubuntu/dev
#  - source: source
#    destination: /webapps/myApp
#hooks:
#  BeforeInstall:
#    - location: Scripts/UnzipResourceBundle.sh
#    - location: Scripts/UnzipDataBundle.sh
#  AfterInstall:
#    - location: Scripts/RunResourceTests.sh
#      timeout: 180
#  ApplicationStart:
#    - location: Scripts/RunFunctionalTests.sh
#      timeout: 3600
#  ValidateService:
#    - location: Scripts/MonitorService.sh
#      timeout: 3600
#      runas: codedeployuser